### ISSUE TITLE
Add External Dependencies to Open-CE Env Files

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce#44]
If we add external dependencies to the open-ce env file, the compatibility of those versions and all the internal dependencies can be verified.

This is a step towards facilitating the creation of custom environments with packages outside the scope of Open-CE.

My idea is to add another section to the yaml files. Something like:

```yaml
imported_envs:
  - pytorch-env.yaml
  - tensorflow-env.yaml

{% if build_type == 'cuda' %}
channels:
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
{% endif %}

packages:
  - feedstock : horovod
  - feedstock : openmpi

external-packages:
  - package1 1.2
  - package2 2.3
```
